import { chromium, webkit, expect } from '@playwright/test'
import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'

const base=process.env.EDGE_PUBLIC_TEST_URL
if(!base?.startsWith('https://'))throw new Error('Set EDGE_PUBLIC_TEST_URL to the deployed HTTPS demo')
await mkdir('artifacts/public-demo',{recursive:true})
const results=[]
for(const [name,type] of Object.entries({chromium,webkit})) {
  const browser=await type.launch()
  try {
    const context=await browser.newContext({viewport:{width:402,height:874}})
    const page=await context.newPage(), errors=[], external=[], mutations=[]
    page.on('pageerror',e=>errors.push(e.message))
    page.on('request',r=>{
      if(!r.url().startsWith(base))external.push(r.url())
      if(r.method()==='POST' && r.url().includes('/api/'))mutations.push(r.url())
    })
    const response=await page.goto(base+'/?fixture=original')
    assert.equal(response.status(),200)
    assert.match(response.headers()['content-security-policy'],/script-src 'self';/)
    await expect(page.locator('[data-demo-label]')).toContainText('예시')
    await expect(page.locator('[data-screen-label="온보딩 1 뉴스"]')).toBeVisible()
    const animation=()=>page.evaluate(()=>document.getAnimations().find(a=>a.animationName==='obMarqueeA')?.currentTime)
    const before=await animation();await page.waitForTimeout(200)
    assert.ok((await animation())>before)
    await page.getByText('다음',{exact:true}).click()
    await page.getByText('다음',{exact:true}).click()
    await page.getByText('내 ETF 고르기',{exact:true}).click()
    await page.getByText('AI·반도체',{exact:true}).click()
    await page.getByText('1개 테마 선택',{exact:true}).click()
    await page.locator('[data-etfk="AXAI"]').click()
    await page.getByText('1개 담고 시작하기',{exact:true}).click()
    await expect(page.locator('[data-screen-label="홈"]')).toBeVisible()
    await expect(page.locator('[data-sc-name="LiveTicker"]').first()).toHaveText('+2.90%')
    await page.waitForTimeout(800)
    await page.screenshot({path:`artifacts/public-demo/${name}-home.png`})
    await page.locator('[data-sc-name="IconButton"]').first().click()
    await page.locator('input').first().fill('반도체')
    await page.getByText('TIGER 반도체TOP10',{exact:true}).click()
    await expect(page.getByText('₩12,806',{exact:true}).first()).toBeVisible()
    await page.getByText('AI 분석',{exact:true}).click()
    await page.getByText('연결된 분석·출처',{exact:true}).click()
    await expect(page.locator('[data-screen-label="연결된 분석"]').getByText('20일 이동평균',{exact:true})).toBeVisible()
    await page.getByRole('button',{name:'닫기',exact:true}).click()
    await page.getByRole('button',{name:'ETF AI에게 질문'}).click()
    await page.getByRole('textbox',{name:'ETF 질문'}).fill('가격과 분석의 기준일을 설명해 주세요.')
    await page.getByRole('button',{name:'전송',exact:true}).click()
    await expect(page.locator('[data-screen-label="ETF AI 대화"]').getByText(/^예시 답변입니다\./)).toBeVisible()
    await page.screenshot({path:`artifacts/public-demo/${name}-chat.png`})
    await page.goto(base+'/original')
    await page.locator('[data-tab="community"]').click()
    await page.getByText('산다',{exact:true}).click()
    await page.locator('[data-sc-name="IconButton"]').last().click()
    await page.locator('textarea').fill('공개 데모의 기기 저장 검수입니다.')
    await page.getByText('게시',{exact:true}).click()
    await page.reload()
    await page.locator('[data-tab="community"]').click()
    await expect(page.getByText('공개 데모의 기기 저장 검수입니다.',{exact:true})).toBeVisible()
    await page.screenshot({path:`artifacts/public-demo/${name}-community.png`})
    assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('edge.original.preferences.v1')).pollVotes.AXAI),'buy')
    const visitor=await browser.newContext(),other=await visitor.newPage()
    await other.goto(base)
    assert.deepEqual(await other.evaluate(()=>JSON.parse(localStorage.getItem('edge.original.preferences.v1')||'{}').commMine||{}),{})
    await visitor.close()
    assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.deepEqual(mutations,[])
    results.push({browser:name,passed:true,jsErrors:errors.length,externalRequests:external.length,apiMutations:mutations.length})
  } finally {await browser.close()}
}
await writeFile('artifacts/public-demo/results.json',JSON.stringify({base,checkedAt:new Date().toISOString(),results},null,2))
console.log(JSON.stringify(results))
