const {chromium}=require('../../edge/node_modules/@playwright/test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
(async()=>{
 const {indexedCatalog}=await import('../frontend/entities/graph-layout.mjs');
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1600,height:1050}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 try{
  await page.goto('http://127.0.0.1:5186');
  await page.waitForSelector('#scene .node');
  await page.waitForFunction(()=>document.querySelector('#rowCount').textContent.includes('2,766'));
  assert.equal(await page.locator('#scene .node').count(),7);
  await page.screenshot({path:'output/entity-workbench/overview.png',fullPage:true});
  await page.locator('[data-level="1"]').click();
  await page.waitForFunction(()=>Number(document.querySelector('#graphArea').dataset.expanded)>12);
  const initialPopulation=await page.locator('#graphArea').evaluate(el=>({expanded:Number(el.dataset.expanded),total:Number(el.dataset.total)}));
  assert.equal(initialPopulation.expanded,initialPopulation.total,'Initial dictionary must include every letter, without zooming or index jumps');
  await page.locator('#graphArea').hover();
  await page.mouse.wheel(0,100000);
  await page.waitForFunction(()=>[...document.querySelectorAll('.dictionary-label')].some(el=>el.textContent==='ㅎ'));
  assert.equal(await page.locator('#zoom').inputValue(),'100','Plain wheel must scroll to Korean letters without changing zoom');
  assert((await page.locator('#scene .node').count())<150);
  await page.locator('#dictionary').click();
  await page.waitForFunction(()=>document.querySelector('#graphArea').dataset.dictionary==='false');
  const firstCount=await page.locator('#graphArea').getAttribute('data-expanded');
  await page.locator('#zoom').fill('130');await page.locator('#zoom').dispatchEvent('input');
  await page.waitForFunction(n=>Number(document.querySelector('#graphArea').dataset.expanded)>n,Number(firstCount));
  await page.locator('#dictionary').click();
  await page.waitForFunction(()=>document.querySelector('#graphArea').dataset.dictionary==='true');
  await page.locator('#nameIndex button').filter({hasText:'ㅎ'}).click();
  await page.waitForFunction(()=>Number(document.querySelector('#graphArea').dataset.expanded)===Number(document.querySelector('#graphArea').dataset.total));
  assert.equal(await page.locator('#graphArea').evaluate(el=>getComputedStyle(el).scrollbarWidth),'none');
  assert.equal(await page.locator('#tableSource').innerText(),'public.company_profile');
  await page.locator('#expandAll').click();
  const catalog=indexedCatalog(await (await page.request.get('http://127.0.0.1:5186/api/catalog?kind=COMPANY')).json());
  await page.waitForFunction(n=>Number(document.querySelector('#graphArea').dataset.expanded)===n,catalog.total);
  assert(catalog.total>2400);
  assert((await page.locator('#scene .node').count())<150,'Only viewport nodes should be mounted');
  await page.locator('[data-move="down"]').click();
  await page.waitForFunction(()=>document.querySelector('#graphArea').scrollTop>0);
  assert.equal(await page.locator('#dictionary').getAttribute('aria-pressed'),'true');
  assert(await page.locator('#graphArea').evaluate(el=>el.scrollWidth>el.clientWidth));
  await page.locator('#dictionary').click();
  await page.waitForFunction(()=>document.querySelector('#graphArea').dataset.dictionary==='false');
  await page.locator('#dictionary').click();
  await page.waitForFunction(()=>document.querySelector('#graphArea').dataset.dictionary==='true');
  const graphBox=await page.locator('.graph-panel').boundingBox(),dataBox=await page.locator('.data-panel').boundingBox();
  assert(graphBox.width>dataBox.width*2);
  await page.locator('[data-move="last"]').click();
  const last=catalog.rows.at(-1);
  await page.waitForSelector(`[data-entity-id="${last.entity_id}"]`);
  const areaBox=await page.locator('#graphArea').boundingBox();
  const lastBox=await page.locator(`[data-entity-id="${last.entity_id}"]`).boundingBox();
  assert(lastBox.x>=areaBox.x && lastBox.x+lastBox.width<=areaBox.x+areaBox.width);
  assert(lastBox.y>=areaBox.y && lastBox.y+lastBox.height<=areaBox.y+areaBox.height);
  await page.screenshot({path:'output/entity-workbench/all-companies-last.png',fullPage:true});
  const beforeDrag=await page.locator('#graphArea').evaluate(el=>({x:el.scrollLeft,y:el.scrollTop}));
  await page.mouse.move(lastBox.x+30,lastBox.y+30);
  await page.mouse.down({button:'middle'});await page.mouse.move(lastBox.x+110,lastBox.y+90,{steps:8});await page.mouse.up({button:'middle'});
  await page.waitForFunction(p=>document.querySelector('#graphArea').scrollLeft<p.x&&document.querySelector('#graphArea').scrollTop<p.y,beforeDrag);
  assert.equal(await page.locator('#graphTitle').innerText(),'한국 기업 · 전체 탐색');
  await page.locator('[data-move="last"]').click();
  await page.locator(`[data-entity-id="${last.entity_id}"]`).click();
  await page.waitForFunction(id=>document.querySelector('#filter').textContent.includes(id),last.entity_id);
  await page.locator('[data-level="1"]').click();
  await page.locator('[data-move="last"]').click();
  await page.waitForFunction(id=>document.querySelector(`[data-entity-id="${id}"] > rect`)?.getBoundingClientRect().width>0,last.entity_id);
  // Read from the live document: the virtual canvas replaces nodes on scroll frames.
  const expansionWidth=await page.evaluate(id=>document.querySelector(`[data-entity-id="${id}"] > rect`).getBoundingClientRect().width,last.entity_id);
  const expansionZoom=await page.locator('#zoom').inputValue();
  await page.locator(`[data-entity-id="${last.entity_id}"]`).dblclick();
  await page.waitForFunction(()=>document.querySelector('#graphTitle').textContent.startsWith('연결 전체'));
  const expandedWidth=await page.locator('#scene .node > rect').first().evaluate(el=>el.getBoundingClientRect().width);
  assert(Math.abs(expandedWidth-expansionWidth)<1,`Double-click expansion must preserve the visible card size: ${expansionWidth} -> ${expandedWidth}`);
  assert.equal(await page.locator('#zoom').inputValue(),expansionZoom);
  assert((await page.locator('#scene .edge-hit').count())>0);
  await page.locator('#scene .node').filter({hasText:'company_profile'}).first().dblclick();
  await page.waitForFunction(()=>document.querySelector('#inspector .row-source strong')?.textContent==='public.company_profile');
  assert(Math.abs(await page.locator('#scene .node > rect').first().evaluate(el=>el.getBoundingClientRect().width)-expansionWidth)<1,'Repeated expansion must not reset scale');
  await page.setViewportSize({width:1500,height:1000});
  await page.waitForFunction(width=>Math.abs(document.querySelector('#scene .node > rect').getBoundingClientRect().width-width)<1,expansionWidth);
  await page.setViewportSize({width:1600,height:1050});
  await page.locator('#entitySearch').fill('삼성전자');
  await page.waitForSelector('#searchResults button');
  await page.locator('#searchResults button').filter({hasText:'ACTOR'}).first().click();
  await page.waitForFunction(()=>document.querySelector('#graphTitle').textContent==='실제 행과 FK');
  assert((await page.locator('#scene .node').count())>=6);
  await page.locator('#orientation').click();await page.locator('#fit').click();
  await page.locator('#scene .edge-hit[aria-label="issuer_actor_id"]').first().focus();
  await page.keyboard.press('Enter');
  await page.waitForSelector('[data-verdict="confirmed"]');
  assert.equal(await page.locator('.compare article').count(),2);
  const sources=await page.locator('.compare .row-source strong').allTextContents();
  assert(sources.includes('public.equity_profile'));assert(sources.includes('public.company_profile'));
  assert((await page.locator('#scene .edge-label').first().evaluate(el=>parseFloat(getComputedStyle(el).fontSize)))>=13);
  assert.equal(await page.locator('#tableSource').innerText(),'public.entity');
  await page.screenshot({path:'output/entity-workbench/compare.png',fullPage:true});
  await page.locator('#companyDocs').click();
  await page.waitForSelector('[data-doc]');
  assert((await page.locator('[data-doc]').count())>=1);
  await page.locator('[data-doc]').first().click();
  await page.waitForFunction(()=>document.querySelector('#tableSelect').value==='document');
  await page.locator('[data-phase="1"]').click();
  await page.waitForSelector('[data-alias]');
  await page.locator('[data-alias]').filter({hasText:'현대자동차'}).click();
  await page.waitForSelector('#reviewNote');
  await page.locator('#reviewNote').fill('E2E_TEMP_VALIDATION');
  await page.locator('[data-verdict="needs_review"]').click();
  await page.waitForFunction(()=>document.querySelector('#reviews').textContent.includes('E2E_TEMP_VALIDATION'));
  await page.reload();await page.waitForFunction(()=>document.querySelector('#reviews').textContent.includes('E2E_TEMP_VALIDATION'));
  await page.locator('#tableSelect').selectOption('instrument');
  await page.locator('#rowSearch').fill('0001A0');
  await page.waitForFunction(()=>document.querySelector('#rowCount').textContent.startsWith('1행'));
  assert((await page.locator('#dataTable').innerText()).includes('0001A0'));
  await page.locator('#clearFilter').click();await page.waitForFunction(()=>document.querySelector('#rowCount').textContent.includes('2,804'));
  await page.locator('th[data-sort="ticker"]').click();
  await page.waitForFunction(()=>document.querySelector('th[data-sort="ticker"]').textContent.includes('↑'));
  await page.locator('#next').click();await page.waitForFunction(()=>document.querySelector('#page').textContent==='2');
  const denied=await page.request.post('http://127.0.0.1:5186/api/reviews',{data:{status:'confirmed'}});assert.equal(denied.status(),403);
  const badSort=await page.request.get('http://127.0.0.1:5186/api/rows?table=entity&sort=invalid_column');assert.equal(badSort.status(),400);
  await page.setViewportSize({width:850,height:1100});
  await page.screenshot({path:'output/entity-workbench/narrow.png',fullPage:true});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  assert.deepEqual(errors,[]);
  const summary={passed:true,expanded_companies:catalog.total,checks:['name index jump expands hidden group','middle-button drag over node','hidden graph scrollbars','explicit table provenance','readable relationship labels','overview','type abstraction','continuous population zoom','complete company expansion','dictionary rows and toggle','larger graph area','single versus double click','inbound and outbound expansion','last entity reachable and selectable','bounded viewport rendering','entity lookup','record FK graph','layout orientation','two-row comparison','company documents','aliases','review persistence','alphanumeric search','sort','pagination','write token','invalid SQL identifiers','narrow layout'],browser_errors:errors};
  fs.writeFileSync('output/entity-workbench/browser-verification.json',JSON.stringify(summary,null,2));console.log(summary);
 }finally{await browser.close();require('node:child_process').execFileSync('.cache/news-filter-benchmark/Scripts/python.exe',['-c',"import sqlite3; from contextlib import closing; from pathlib import Path; p=Path('output/entity-workbench/reviews.sqlite3'); c=sqlite3.connect(p) if p.exists() else None; c and c.execute('DELETE FROM review WHERE note=?',('E2E_TEMP_VALIDATION',)); c and c.commit(); c and c.close()"]);}
})().catch(e=>{console.error(e);process.exitCode=1;});
